# Reporter class which acts as container for all the information used for the 
# report.
# All elements like images, tables and text are already converted to HTML and 
# prepared for the representation in the HTML report by functions from script
# html_util.R.
# The responsibility of the Reporter class is to put everythign together and add/
# replace the related tokens in the template. 
# The reporter class uses a dictionary to mape seide menu elements to sections.
# The final HTML based report is generated by the function create_html_webpage().

# Source: https://livefreeordichotomize.com/2017/01/24/custom-javascript-visualizations-in-rmarkdown/
send_df_to_js <- function(df){
  cat(paste('<script>var data = ',toJSON(df),'</script>', sep=""))
}

get_indentation <- function(length) {
  return(paste(rep(' ',length),collapse=''))
}

create_html_title <- function(title, name, date) {
  s1 <- paste0('<h1>',title,'</h1>')
  s2 <- paste0(get_indentation(10),'<h4>',name,'</h4>')
  s3 <- paste0(get_indentation(10),'<h4>',date,'</h4>')
  return(paste(s1,s2,s3,sep='\n'))
}

# Expects a list of HTML tables as tags.
# combine_html_tables <- function(tables) {
#   # add div around each table:
#   # <div class="floated_table">
#   #     ...
#   # </div>
#   # class "floated_table" provides style="float: left;"
#   tag_list <- c()
#   for (table in tables) {
#     tag <- paste0('<div class="floated_table">',table,'</div>')
#     tag_list <- c(tag_list, tag)
#   }
#   return(tag)
# }

save_as_static_html_table <- function(file, data) {
  s1 <- '<!DOCTYPE html><html lang="en"><head><title>Table</title>'
  s2 <- '<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">'
  s3 <- '<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>'
  s4 <- '<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>'
  s4 <- '</head><body>'
  s5 <- data %>%
    knitr::kable() %>%
    kableExtra::kable_styling(bootstrap_options = c("striped", "hover"), full_width = F)
  s6 <- '</body></html>'   
  html_table <- paste(s1,s2,s3,s4,s5,s6,sep='\n')
  html_table <- stringr::str_replace(html_table, 'margin-left: auto;', 'margin-left: 0;')
  fileConn <- file(file)
  writeLines(html_table, fileConn)
  close(fileConn)
  # knitr::kable(data, "html") %>%
  #   kableExtra::kable_styling(bootstrap_options = c("striped", "hover")) %>%
  #   cat(., file = file)
  # s1 <- data %>% 
  #   knitr::kable() %>% 
  #   kableExtra::kable_styling(bootstrap_options = c("striped", "hover"), full_width = F) 
  # #s1 <- paste0(get_indentation(10),s1) # TODO: This only indents the first element!
  # html_table <- paste(s1,'',sep='') # TODO: Why we need paste() here?
  # fileConn <- file(file)
  # writeLines(html_table, fileConn)
  # close(fileConn)
}

save_as_dynamic_html_table <- function(file, data) {
  widget <- DT::datatable(data, 
                          filter = 'top', 
                          options = list(paging = TRUE))
  #s2 <- htmltools::tagList(htmlwidgets:::toHTML(widget))
  #s2 <- htmltools::as.tags(widget)
  #gg <- htmltools::renderTags(s2)
  
  htmlwidgets::saveWidget(widget, file, selfcontained = FALSE)
  
  # s2 <- htmltools::as.tags(widget)
  # label <- s2[[2]]$attribs$`data-for` # Example: "htmlwidget-eb336425ed38be1d603a"
  # table_content <- as.character(s2[[2]]$children[[1]]) # Script content with data: {"x":{"filter":"top",...}
  # e1 <- '<div id="htmlwidget_container">\n'
  # e2 <- paste0('<div id="',label,'" style="width:960px;height:500px;" class="datatables html-widget"></div>\n')
  # e3 <- '</div>\n'
  # e4 <- paste0('<script type="application/json" data-for="',label,'">\n')
  # e5 <- '</script>\n'
  # e6 <- paste0('<script type="application/htmlwidget-sizing" data-for="',label,'">\n')
  # e7 <- '{"viewer":{"width":450,"height":350,"padding":15,"fill":true},"browser":{"width":960,"height":500,"padding":40,"fill":false}}\n'
  # e8 <- '</script>\n'
  # full_html <- paste0(e1,e2,e3,e4,table_content,e5,e6,e7,e8)
  # return(full_html)
  # table_tags <- htmltools::as.tags(DT::datatable(data, 
  #                                                filter = 'top', 
  #                                                options = list(paging = TRUE)))
  #s2 <- as.character(table_tags)
  #s2 <- table_tags
  #return(paste(s1,s2,sep='\n'))
  #return(s2)
}

# COMMENT: Not work, combine images for example by ggarrange() from ggpubr.
# create_html_images_horizontally = function(file1, file2, description) {
#   s1 <- ''
#   if (nchar(description) > 0) {
#     s1 <- paste0(get_indentation(10),'<h4>',description,'</h4>')
#   } 
#   s2 <- paste0(get_indentation(10),"<img src='",file1,"' alt='No image found' class='img-responsive'>")
#   s3 <- paste0(get_indentation(10),"<img src='",file2,"' alt='No image found' class='img-responsive'>")
#   div_start <- '<div class="horizontal-images-align">'
#   div_end <- '</div>'
#   spacer <- '&nbsp;&nbsp;'
#   return(paste(div_start,s1,s2,spacer,s3,div_end,sep='\n'))
# }  

create_html_image <- function(file, description, width, height) {
  s1 <- ''
  if (nchar(description) > 0) {
    s1 <- paste0(get_indentation(10),'<h4>',description,'</h4>')
  } 
  s2 <- paste0(get_indentation(10),
  '<img src="',file,'" alt="No image found" style="width:',width,';height:',height,';" class="img-responsive">')
  return(paste(s1,s2,sep='\n'))
}

# '<object type="text/html" data="',path,'" style="width:100%;height:100vh;">\n'
# s2 <- paste0('<object type="text/html" data="',file,'" style="width:',width,';height:',heigth,';">\n')
create_html_table <- function(file, description, width, height) {
  s1 <- ''
  if (nchar(description) > 0) {
    s1 <- paste0(get_indentation(10),'<h4>',description,'</h4>\n')
  }
  s2 <- paste0(get_indentation(10),'<div class="html-table">\n')
  s3 <- paste0(get_indentation(12),'<object type="text/html" data="',file,
               '" style="width:',width,';height:',height,';">\n')
  s4 <- paste0(get_indentation(12),'  Error: HTML table could not be displayed.\n')
  s5 <- paste0(get_indentation(12),'</object>\n')
  s6 <- paste0(get_indentation(10),'</div>')
  return(paste(s1,s2,s3,s4,s5,s6,sep='')) 
}

create_html_tables_horizontally <- function(file1, file2, description, width, height) {
  s1 <- ''
  if (nchar(description) > 0) {
    s1 <- paste0(get_indentation(10),'<h4>',description,'</h4>\n')
  }
  s2 <- paste0(get_indentation(10),'<div class="horizontal-tables">\n')
  s3 <- paste0(get_indentation(12),'<table>\n') 
  s4 <- paste0(get_indentation(14),'<tr>\n') 
  s5 <- paste0(get_indentation(16),'<td>\n')
  f1 <- paste0(get_indentation(18),'<object type="text/html" data="',file1,
               '" style="width:',width,';height:',height,';">\n')
  f2 <- paste0(get_indentation(18),'<object type="text/html" data="',file2,
               '" style="width:',width,';height:',height,';">\n')
  o1 <- paste0(get_indentation(18),'  Error: HTML table could not be displayed.\n')
  o2 <- paste0(get_indentation(18),'</object>\n')
  e1 <- paste0(get_indentation(16),'</td>\n')
  e2 <- paste0(get_indentation(14),'</tr>\n')
  e3 <- paste0(get_indentation(12),'</table>\n')
  e4 <- paste0(get_indentation(10),'</div>')
  return(paste(s1,s2,s3,s4,s5,f1,o1,o2,e1,s5,f2,o1,o2,e1,e2,e3,e4,sep='')) 
}

create_html_text <- function(description) {
  return(paste0(get_indentation(10),'<p>',description,'</p>'))
}


HTMLReporter <- R6Class(
    "Reporter", 
    public = list(
    # Constructor:
      # parameter file: html template file
    initialize = function(file) {
        private$html_template <- private$load_template(file)
    },
    # Public methods:
    add_title = function(title, name, date) {
        private$title_element <- create_html_title(title, name, date)
        invisible(self)
    },
    add_image = function(section, description, file, width, height) {
        html_img <- create_html_image(file, description, width, height)
        private$add_html_to_dict(section, html_img)
    },
    add_two_tables_horizontally = function(section, description, file1, file2, width, height) {
        html_tables <- create_html_tables_horizontally(file1, file2, description, width, height)
        private$add_html_to_dict(section, html_tables)
    },  
    add_table = function(section, description, file, width, height) {
        html_table <- create_html_table(file, description, width, height)
        private$add_html_to_dict(section, html_table)
    },
    add_text = function(section, description) {
        html_text <- create_html_text(description)
        private$add_html_to_dict(section, html_text)
    },
    create_html_webpage = function(file, section_list) {
        # TODO:
        # Iterate over the key value pairs in the side_menu_section_dict
        # and create html for the side menu with the keys and the content with 
        # the values and automatically generated section IDs, and
        # replace the tokens in the template.
        # Then store the result as html file for the path given.
        menu <- private$create_side_menu(section_list)
        sections <- private$create_sections(section_list)
        html_code <- private$replace_tokens(private$html_template,
                                            private$title_element,
                                            menu,
                                            sections)
        fileConn <- file(file)
        writeLines(html_code, fileConn)
        close(fileConn)
    }
  ),
  private = list(
      # Private attributes:
      title_element = NULL,
      side_menu_section_dict = hash::hash(),
      html_template = NULL,
      # Private methods:
      load_template = function(file) {
        return(readr::read_file(file))
      },
      add_html_to_dict= function(section, html) {
        if (length(private$side_menu_section_dict) == 0) {
          private$side_menu_section_dict[[section]] <- html
        } else {
          dict_keys <- keys(private$side_menu_section_dict)
          if (section %in% dict_keys) {
            private$side_menu_section_dict[[section]] <- c(
              private$side_menu_section_dict[[section]],
              html)
          } else {
            private$side_menu_section_dict[[section]] <- html
          }
        }  
        invisible(self)
      },
      # Side menu has the following structure:
      # <li><a href="#section_id_1">the section</a></li>
      create_side_menu = function(elements) {
        #elements <- keys(private$side_menu_section_dict)
        section_counter <- 1
        menu <- c()
        for (element in elements) {
          s1 <- '<li><a href="#'
          s2 <- paste0("section_id_",section_counter,'">')
          s3 <- element
          s4 <- '</a></li>'
          if (section_counter == 1) {
            menu <- c(menu,paste(s1,s2,s3,s4,sep=''))
          } else {
            elem <- paste(s1,s2,s3,s4,sep='')
            menu <- c(menu,paste0(get_indentation(10),elem))
          } 
          section_counter <- section_counter + 1
        }
        return(paste(menu, collapse = '\n'))
      },
      # The sections have the following form:
      # <section id="section_id_1">
      # ...
      # </section>
      create_sections = function(elements) {
        #elements <- keys(private$side_menu_section_dict)
        sections <- c()
        section_counter <- 1
        for (element in elements) {
          if (section_counter == 1) {
            s1 <- paste0('<section id="section_id_',section_counter,'">')
          } else {
            s1 <- paste0(get_indentation(8),'<section id="section_id_',section_counter,'">')
          }  
          s2 <- paste0(get_indentation(10),'<h2>',element,'</h2>')
          content <- private$side_menu_section_dict[[element]]
          tags <- paste(content, collapse = '\n')
          s3 <- paste0(get_indentation(8),'</section>')
          sections <- c(sections,paste(s1,s2,tags,s3,sep='\n'))
          section_counter <- section_counter + 1
        }  
        return(paste(sections, collapse = '\n'))
      },
      # Replacing the tokens in the template to generate the full web page.
      replace_tokens = function(template, title, menu, section) {
        pat_val_list <- c(
          HTML_ELEMENT_TITLE = title,
          HTML_ELEMENT_SIDE_MENU = menu,
          HTML_ELEMENT_SECTION = section
        )  
        html_code <- template %>% stringr::str_replace_all(pat_val_list)
        return(html_code)
      }
  )          
)



  
    