# Reporter class which acts as container for all the information used for the 
# report.
# All elements like images, tables and text are already converted to HTML and 
# prepared for the representation in the HTML report by functions from script
# html_util.R.
# The responsibility of the Reporter class is to put everythign together and add/
# replace the related tokens in the template. 
# The reporter class uses a dictionary to mape seide menu elements to sections.
# The final HTML based report is generated by the function create_html_webpage().

library(R6)
library(hash)
library(tidyverse)
library(jsonlite)

# Source: https://livefreeordichotomize.com/2017/01/24/custom-javascript-visualizations-in-rmarkdown/
send_df_to_js <- function(df){
  cat(paste('<script>var data = ',toJSON(df),'</script>', sep=""))
}

get_indentation <- function(length) {
  return(rep(' ', length))
}

create_html_title = function(title, name, date) {
  s1 <- paste0('<h1>',title,'</h1>')
  s2 <- paste0('<h4>',name,'</h4>')
  s3 <- paste0('<h4>',date,'</h4>')
  return(paste(s1,s2,s3,sep='\n'))
}

# Expects a list of HTML tables as tags.
combine_html_tables <- function(tables) {
  # add div around each table:
  # <div class="floated_table">
  #     ...
  # </div>
  # class "floated_table" provides style="float: left;"
  tag_list <- c()
  for (table in tables) {
    tag <- paste0('<div class="floated_table">',table,'</div>')
    tag_list <- c(tag_list, tag)
  }
  return(tag)
}

create_static_html_table = function(description, data) {
  s1 <- ''
  if (nchar(description) > 0) {
    s1 <- paste0('<h4>',description,'</h4>')
  } 
  s2 <- data %>% 
    kable::kable() %>% 
    kable_styling(bootstrap_options = c("striped", "hover"), full_width = F) 
  return(paste(s1,s2,sep='</br>'))
}

create_dynamic_html_table = function(description, data, type) {
  s1 <- ''
  if (nchar(description) > 0) {
    s1 <- paste0('<h4>',description,'</h4>')
  } 
  table_tags <- htmltools::as.tags(DT::datatable(data, 
                                                 filter = 'top', 
                                                 options = list(paging = TRUE)))
  s2 <- as.character(table_tags)
  return(paste(s1,s2,sep='</br>'))
}

create_html_image = function(description, path) {
  s1 <- ''
  if (nchar(description) > 0) {
    s1 <- paste0('<h4>',description,'</h4>')
  } 
  s2 <- paste0("<img src='",path,"' alt='No image found' class='img-responsive'>")
  return(paste(s1,s2,sep='\n'))
}

create_html_text = function(description) {
  return(paste0('<p>',description,'</p>'))
}


HTMLReporter <- R6Class(
    "Reporter", 
    public = list(
    # Constructor:
      # parameter file: html template file
    initialize = function(file) {
        private$html_template <- private$load_template(file)
    },
    # Public methods:
    add_title = function(title, name, date) {
        private$title_element <- create_html_title(title, name, date)
        invisible(self)
    },
    add_image = function(section, description, path) {
        html_img <- create_html_image(description, path)
        if (length(private$side_menu_section_dict) == 0) {
          private$side_menu_section_dict[[section]] <- html_img
        } else {
          dict_keys <- keys(private$side_menu_section_dict)
          if (section %in% dict_keys) {
            private$side_menu_section_dict[[section]] <- c(
              private$side_menu_section_dict[[section]],
              html_img)
          } else {
            private$side_menu_section_dict[[section]] <- html_img
          }
        }
        invisible(self)
    },
    add_table = function(section, description, data, type) {
        dict_keys <- keys(private$side_menu_section_dict)
        if (section %in% dict_keys) {
            html_table <- create_html_table(description, data, type)
            private$side_menu_section_dict[[menu_element]] <- c(
              private$side_menu_section_dict[[menu_element]],
              html_table)
        } else {
            stop(paste0('Could not find in side menu provided section ',section))
        }
        invisible(self)
    },
    add_text = function(section, description) {
        dict_keys <- keys(private$side_menu_section_dict)
        if (section %in% dict_keys) {
            html_text <- create_html_text(description)
            private$side_menu_section_dict[[menu_element]] <- c(
              private$side_menu_section_dict[[menu_element]],
              html_text)
        } else {
            stop(paste0('Could not find in side menu provided section ',section))
        }
        invisible(self)
    },
    create_html_webpage = function(file) {
        # TODO:
        # Iterate over the key value pairs in the side_menu_section_dict
        # and create html for the side menu with the keys and the content with 
        # the values and automatically generated section IDs, and
        # replace the tokens in the template.
        # Then store the result as html file for the path given.
      menu <- private$create_side_menu()
      sections <- private$create_sections()
      html_code <- private$replace_tokens(private$html_template,
                                          private$title_element,
                                          menu,
                                          sections)
      fileConn <- file(file)
      writeLines(html_code, fileConn)
      close(fileConn)
    }
  ),
  private = list(
      # Private attributes:
      title_element = NULL,
      side_menu_section_dict = hash::hash(),
      html_template = NULL,
      # Private methods:
      load_template = function(file) {
        return(readr::read_file(file))
      },
      # Side menu has the following structure:
      # <li><a href="#section_id_1">the section</a></li>
      create_side_menu = function() {
        elements <- keys(private$side_menu_section_dict)
        section_counter <- 1
        menu <- c()
        for (element in elements) {
          s1 <- '<li><a href="#'
          s2 <- paste0("section_id_",section_counter,'">')
          s3 <- element
          s4 <- '</a></li>'
          menu <- c(menu,paste(s1,s2,s3,s4,sep=''))
          section_counter <- section_counter + 1
        }
        return(paste(menu, collapse = '\n'))
      },
      # The sections have the following form:
      # <section id="section_id_1">
      # ...
      # </section>
      create_sections = function() {
        elements <- keys(private$side_menu_section_dict)
        sections <- c()
        section_counter <- 1
        for (element in elements) {
          s1 <- paste0('<section id="section_id_',section_counter,'">')
          s2 <- paste0('<h2>',element,'</h2>\n')
          content <- private$side_menu_section_dict[[element]]
          tags <- paste(content, collapse = '\n')
          s3 <- '</section>'
          sections <- c(sections,paste(s1,s2,tags,s3,sep='\n'))
          section_counter <- section_counter + 1
        }  
        return(paste(sections, collapse = '\n'))
      },
      # Replacing the tokens in the template to generate the full web page.
      replace_tokens = function(template, title, menu, section) {
        pat_val_list <- c(
          HTML_ELEMENT_TITLE = title,
          HTML_ELEMENT_SIDE_MENU = menu,
          HTML_ELEMENT_SECTION = section
        )  
        html_code <- template %>% stringr::str_replace_all(pat_val_list)
        return(html_code)
      }
  )          
)



  
    